bin/templates/cordova/version, cordova-lib/cordova.js, package.json
electron
- Corrects the version information of the platform to `1.0.0-dev`
> Since the platform has never been released, this PR ensure that we release on the proper version.
```
$ npm t
```
=> Updated Correct Version Information

package-lock.json, package.json
electron
This PR contains final preparations for the Cordova 9 release goals. 
See [Cordova 9 Release Plan](https://github.com/apache/cordova/issues/10).
- Bumped Cordova Dependencies
- `cordova-common@^3.1.0`
- Bumped ESLint dependencies
- `eslint@^5.12.0`
- `eslint-config-semistandard@^13.0.0`
- `eslint-plugin-import@^2.14.0`
- `eslint-plugin-node@^8.0.1`
- Updated Testing and Code Coverage dependencies
- `jasmine@^3.3.1`
- `nyc@^13.1.0`
- Bump `fs-extra@^7.0.1`
- Updated Electron and Builder Dependencies
- `electron@^4.0.1`
- `electron-builder@^20.38.4`
- `npm t`
- ESLint
- Code Coverage (unit testing)
- Platform Add & Prepare
```
$ npx cordova@nightly create electronTest com.foobar.electronTest
$ cd ./electronTest
$ npx cordova@nightly platform add …
```
=> Electron Platform Release Preparation (Cordova 9)

bin/lib/create.js, bin/templates/cordova/lib/prepare.js, bin/templates/project/cdv-electron-settings.json, bin/templates/project/main.js
------------------------------------------
------------------------------------------
Electron
------------------------------------------
------------------------------------------
Create a setting json file, where we could store necessary settings for electron platform.
When running or building electron platform users can pass in `--release` flag through cli. 
Depending on that flag set an appropriate `isRelease` value.
Later check that value `isRelease` value and depending on that value, open or close the Dev Tools window on the launch.
This file could be used in the future to store other necessary options and configs for electron platform. 
------------------------------------------
------------------------------------------
Tested 4 cases with 3 node version 6.16.0, 8.15.0 and 10.15.0 …
=> Create electron settings json

bin/templates/cordova/lib/build/base.json, bin/templates/cordova/lib/build/linux.json
electron
- Removed the `type` param from Linux default build configs. This is not a valid param for Linux and causes builds to stop.
- Bumped and pinned the supported Electron version to `4.0.1` to match with package.json.
```
$ npx cordova@nightly create electronTest com.foobar.electronTest electronTest && cd $_
$ npx cordova@nightly platform add github:erisu/cordova-electron\#build-fix
$ npx cordova@nightly build electron
```
=> Electron Build Improvements

bin/templates/cordova/lib/ManifestJsonParser.js, bin/templates/cordova/lib/PackageJsonParser.js, bin/templates/cordova/lib/SettingJsonParser.js, bin/templates/cordova/lib/prepare.js, tests/spec/fixtures/test-config-1.xml, tests/spec/fixtures/test-config-2.xml, tests/spec/fixtures/test-config-empty.xml, tests/spec/unit/templates/cordova/lib/ManifestJsonParser.spec.js, tests/spec/unit/templates/cordova/lib/PackageJsonParser.spec.js, tests/spec/unit/templates/cordova/lib/SettingJsonParser.spec.js, tests/spec/unit/templates/cordova/lib/prepare.spec.js
none
Refactor prepase.js and increase Code Coverage
Created new files for SettingJsonParser, PackageJsonParser and ManifestJsonParser classes. Added Unit Tests for the SettingJsonParser, PackageJsonParser and ManifestJsonParser class and increased prepare.js Code Coverage
npm t
=> Refactor prepare.js, increase test coverage

bin/templates/cordova/lib/prepare.js, tests/spec/fixtures/test-config-1.xml, tests/spec/fixtures/test-config-2.xml, tests/spec/unit/templates/cordova/lib/prepare.spec.js
none
Increase test coverage
Wrote tests for module.exports.prepare. Fixed an issue in prepareIcons, discovered by testing. Also, removed my repo data from mock config.xml.
npm t
=> Add module.exports.prepare Test with Fix

bin/templates/cordova/Api.js, bin/templates/cordova/handler.js, tests/spec/fixtures/testapp/config.xml, tests/spec/fixtures/testplugin/src/electron/sample.json, tests/spec/fixtures/testplugin/www/plugin.js, tests/spec/unit/Api.spec.js, tests/spec/unit/handler.spec.js
cordova-electron
Adding tests to Api.spec.js to improve tests coverage.
Some files (Api.js and handler.js) are changed accroding to adding tests.
Especially API.js is improved to choose `root` directory in tests. (Same as `cordova-ios`)
If the `root` directory in API.js is fixed to parent directory of `API.js` as 
```
this.root = path.resolve(__dirname, '..');
```
, files are generated under the `/bin/templates/project` by `API.js`. 
(For example, `electron.json`, `www/cordova_plugins.js` are created by API.js.)
It is not desirable. 
We want to all generated files are under the `/temp` dir.
Therefore `API.js` is changed to
```
this.root = platformRootDir || path.resolve(__dirname, '..');
```
to use platformRootDir is it is specified. (This is same as `cordova-ios`)
The `tmpDir` is changed …
=> Add tests to Api.spec.js

tests/spec/unit/Api.spec.js
cordova-electron
In my previous PR, some of async tasks lack `done()` methods that are necessary with legacy ES5/jasmine format.
The modern ES2015/jasmine3 format is better.
Updating `Api.spec.js` with modern ES2015/jasmine format instead of using legacy `done()` method for async tasks.
`npm run test`
=> Updated Async Tests Api.spec.js to Return Promise

README.md, tests/spec/fixtures/test-config-1.xml, tests/spec/fixtures/test-config-2.xml, tests/spec/fixtures/test-config-empty.xml, tests/spec/fixtures/testapp/config.xml
none
- Preparing branch for release.
Applies to files that are missing the Apache License headers.
- none
=> Apply Missing Apache License Header

bin/templates/cordova/Api.js, bin/templates/cordova/lib/prepare.js, bin/templates/cordova/lib/run.js, tests/spec/unit/Api.spec.js, tests/spec/unit/templates/cordova/lib/prepare.spec.js
none
- Cleanup before release
- Fixes platform add failure due to lost scoping.
- Remove stubbed tests in favor for parent method test.
- Removed un-needed comments.
- Refactor to use emit over console log.
- Spy on emit for testing and also remove un-needed printout during testing.
- Fixes lost scoping when prepare is called.
- `npm t`
- Platform Add, Build and Run Test
```
npx cordova@nightly create electronTest com.foobar.electronTest electronTest && cd $_
npx cordova@nightly platform add github:erisu/cordova-electron\#test-cleanup
npx cordova@nightly build electron
npx cordova@nightly run electron --nobuild
```
=> Code Cleanup & Refactor

cordova-js-src/confighelper.js, cordova-js-src/exec.js, cordova-js-src/platform.js
none
Remove warnings when running cordova-js grunt compile command.
```
Executing: grunt compile:electron --platformVersion=1.1.0-dev
Running "compile:electron" (compile) task
WARNING: file name /apache/cordova/cordova-electron/cordova-js-src/confighelper.js is missing the license header
WARNING: file name /apache/cordova/cordova-electron/cordova-js-src/exec.js is missing the license header
WARNING: file name /apache/cordova/cordova-electron/cordova-js-src/platform.js is missing the license header
```
Updated the file's header license to match the Cordova-JS recognized pattern.
- Run cordova-js grunt command.
=> Correct File Header Licenses for Cordova JS Compile CMD

bin/templates/cordova/handler.js, tests/spec/unit/handler.spec.js
android
Fix the plugin asset install issue detected by mobilespec for release.
Updated `fs.copySync` with valid arguments and added a `mkdirp` call before `copySync`.
```
Installing "cordova-plugin-test-framework" for electron
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-test-framework': Error: Uh oh!
ENOENT: no such file or directory, stat '/apache/cordova/mobilespec/plugins/cordova-plugin-test-framework/www/assets/*'
at Object.fs.statSync (fs.js:948:11)
at Object.statSync (/apache/cordova/mobilespec/platforms/electron/cordova/node_modules/graceful-fs/polyfills.js:295:24)
at checkStats (/apache/cordova/mobilespec/platforms/electron/cordova/node_modules/fs-extra/lib/copy-sync/copy-sync.js:171:22)
at checkPaths …
```
=> Asset Install Fix from Mobilespec Report

DOCUMENTATION.md, bin/templates/cordova/lib/run.js, tests/spec/unit/templates/cordova/lib/run.spec.js
electron
Running electron platform with cordova-lib prior 9.x.x breaks. This is because prior to Cordova 9, the electron platform is added to `cordova-electron` folder, but in the `run.js` we have a static path pointing to `./platforms/electron/www/main.js`. Therefore it's unable to locate the `main.js` and results in an error.
Changed static string in the `run.js` to more "dynamic" approach using `path.resolve` with `__dirname`. Also, updated tests to test this functionality.
Added and ran electron platform with both `cordova (8.1.2)` and `cordova-nighly (9.0.0)` versions. Also, executed automated tests using:
```
npm t
```
=> Update run to work with Cordova CLI prior version 9.x

.npmignore, tests/spec/unit/Api.spec.js
- Remove temp folder after tests
- Add temp folder to .npmignore
electron
This closes #31.
When testing the API's functionality `temp` folder is created. However, after the tests finish it's not deleted. We probably should delete that after we finish testing.
I have refactored the API tests to delete the `temp` folder after tests. Also, I have added the `temp` folder to `.npmignore` just as it is in `.gitignore`.
npm t.
=> Refactor API tests

bin/templates/cordova/lib/build.js, tests/spec/unit/templates/cordova/lib/build.spec.js
electron
Implement unit tests for the `build.js` and make small improvements/fixes in the `build.js` file.
Implemented unit tests for the `build.js`. Refactored `build.js` use `throw Error` instead of `throw`. Also, spotted and fixed a minor platform mapping error while testing.
`npm t`
=> Refactor and test build.js:

bin/templates/project/cdv-electron-main.js, bin/templates/project/cdv-electron-settings.json
electron
Remove Electron Deprecation Warnings.
When previewing debug builds with dev tools open, Electron displays a console warning:
```
Electron Deprecation Warning (nodeIntegration default change) This window has node integration enabled by default. In Electron 5.0.0, node integration will be disabled by default. To prepare for this change, set {nodeIntegration: true} in the webPreferences for this window, or ensure that this window does not rely on node integration and set {nodeIntegration: false}.
```
This PR adds `{ nodeIntegration: false }` as the default value.
- `npm t`
=> Remove nodeIntegration Warning by Setting Default to False

DOCUMENTATION.md, bin/templates/cordova/lib/SettingJsonParser.js, bin/templates/cordova/lib/build.js, bin/templates/cordova/lib/prepare.js, bin/templates/cordova/lib/util.js, bin/templates/project/cdv-electron-main.js, bin/templates/project/cdv-electron-settings.json, tests/spec/unit/templates/cordova/lib/SettingJsonParser.spec.js, tests/spec/unit/templates/cordova/lib/build.spec.js, tests/spec/unit/templates/cordova/lib/prepare.spec.js, tests/spec/unit/templates/cordova/lib/util.spec.js
electron
Provide a way to allow users to modify the Cordova Electron Settings file.
This PR allows users to create a file that will be merged with the defaults and and written to the staging area.
The user can create and place the file anywhere from within the project directory and then provides the link within `config.xml`
Example:
```xml
<platform name="electron">
<preference name="ElectronSettingsFilePath" value="res/electron/settings.json" />
</platform>
```
This file does not have any filename restrictions.
It will be fetched and merged on top of the Cordova defaults.
Example:
Cordova Defaults are:
```json
{
"browserWindow": {
"width": 800,
"height": 600,
"webPreferences": {
"devTools": false,
"nodeIntegration": false
}
}
}
```
If the user would like to support Node.JS and Electron …
=> Support User Defined Electron Settings

bin/templates/cordova/lib/util.js
electron
Cordova Electron 1.0.2 patch release
Added missing Apache license header to util.js
none
=> Added Missing License Header to util.js

tests/spec/unit/create.spec.js
electron
After running tests `create.spec.js` leaves a `temp` directory.
Delete `temp` directory after tests finish.
`npm t`
=> Remove temp dir after create.spec.js tests

bin/templates/cordova/lib/build.js, tests/spec/unit/templates/cordova/lib/build.spec.js
Electron
Fixes #44. You can find more details there.
Apply custom app installer icon when the user is using a custom build configuration. Update `build.js` tests.
```
npm t
```
Also, tested the following use case:
Created a `{project_root}/build.json` file:
```json
{
"electron": {
"mac": {
"package": [
"tar.gz",
"dmg",
"zip"
],
"arch": ["x64"]
}
}
}
```
Then ran `cordova build electron --release`. This generated following settings for `mac` platform in the `{project_root}/platforms/electron/build/builder-effective-config.yaml`:
```yaml
mac:
type: distribution
icon: installer.png
target:
- target: tar.gz
arch:
- x64
- target: dmg
arch:
- x64
- target: zip
arch:
- x64
```
**Results:**
Successfully created all 3 packages with a custom app installer icon.
=> Append installer icon to user build settings

cordova-js-src/confighelper.js, cordova-lib/cordova.js
I am using macOS Mojave, but I think this should affect Windows and Linux as well. This is a fix for the Electron platform in Cordova.
This makes the configuration settings in config.xml work when targeting the Electron platform when running Cordova.
I am specifically working with the [Splashscreen Cordova plugin](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/) and the settings were not loading when Cordova targeting Electron, like this: 
cordova run electron --livereload
The settings I tried to pull in is in the root of my project in config.xml:
<platform name="electron">
<icon src="assets/imgs/icon.png" />
<splash src="assets/imgs/splash.png" />
<preference name="SplashScreen" value="assets/imgs/splash.png" />
<preference name="SplashScreenWidth" …
=> Update the config.xml path in the XHR load eventListener

bin/templates/cordova/lib/prepare.js, tests/spec/unit/templates/cordova/lib/prepare.spec.js
electron
Fixes #47 
Allow users to place the splash screen image inside any folder. If the user defines the correct location in the `config.xml`, we take that image and place in the appropriate folder in the `{project_root}/platfroms/electron/`. As well, set the correct source in the `{project_root}/platfroms/electron/config.xml` file.
npm t
=> Implement Splash Screen handling

bin/templates/cordova/lib/build.js, tests/spec/unit/templates/cordova/lib/build.spec.js
electron
Fixes #50 
Allow to create the top-level mac, linux, windows key contains a set of options instructing electron-builder on how it should build macOS, Linux ar Windows targets. 
```
npm t 
```
Also tested the following scenario.
Created build.json:
```
{
"electron": {
"linux": {
"package": [
"tar.bz2",
{ "appImage": {
"systemIntegration": "doNotAsk"
}
}
],
"arch": ["x64"]
},
"windows": {
"package": ["portable"],
"arch": ["x64"]
}
}
}
```
Ran: 
```
cordova build electron
```
Which resulted in the following `builder-effective-config.yaml` file:
```
...
linux:
target:
- target: tar.bz2
arch:
- x64
- target: appImage
arch:
- x64
icon: installer.png
appImage:
systemIntegration: doNotAsk
win:
target:
- target: portable
arch:
- x64
icon: installer.png
```
=> Append package top-level key options

bin/templates/cordova/lib/build.js, tests/spec/unit/templates/cordova/lib/build.spec.js
electron
Closes #56 
If the platform is Linux and has a category field set in the custom `build.json` file, append category to the `build/linux.json` file.
Tested two cases, when the Linux app category is set and not. 
**When the category is set:**
```json
{
"electron": {
"linux": {
"package": [
"tar.gz"
],
"arch": ["x64"],
"category": "Game"
}
}
```
_**Result:** created and `tar.gz` package with the correct category name - "Game"._
**When the category is not set:**
```json
{
"electron": {
"linux": {
"package": [
"tar.gz"
],
"arch": ["x64"]
}
}
```
_**Result:** created and `tar.gz` package with a default category name - "Utility"._
Also, ran `npm t`.
=> Allow users to set Linux app category

bin/templates/cordova/lib/build.js, bin/templates/cordova/lib/build/linux.json
electron
Remove the `maintainer` option `build/linux.json`, as `maintainer` and `vendor` defaults to the `author` value set in the `{project_root}/platforms/electron/www/package.json`. I believe it's unnecessary to get the option from the `package.json` file and then manually append it to the `build/linux.json` file.
Built all available packages for Linux. As well, ran `npm t`.
=> Remove maintainer option from the Linux build json file

DOCUMENTATION.md, bin/templates/cordova/lib/PackageJsonParser.js, bin/templates/cordova/lib/prepare.js, tests/spec/unit/templates/cordova/lib/PackageJsonParser.spec.js, tests/spec/unit/templates/cordova/lib/prepare.spec.js
electron
Support Bundling Node Modules
fixes: #52
This PR is a possible solution to support the bundling of node_modules inside the Electron built package.
The concept is that when working on an app, we add specific npm packages (`npm i -S <package>`) to the root directory of the Cordova project as a `dependencies`, not `devDependencies`.
For example, if we wanted to use `lodash`:
1. Config the Cordova Project to support `nodeIntegration`.
Follow these guides:
- [Customizing the Application's Window Options](https://github.com/erisu/cordova-electron/blob/bundle-node-modules/DOCUMENTATION.md#customizing-the-applications-window-options)
- [How to support Node.js and Electron APIs?](https://github.com/erisu/cordova-electron/blob/bundle-node-modules/DOCUMENTATION.md#how-to-support-nodejs-and-e …
=> Added Bundle Node Module Support

bin/templates/cordova/lib/PackageJsonParser.js, bin/templates/cordova/lib/prepare.js, tests/spec/unit/templates/cordova/lib/PackageJsonParser.spec.js, tests/spec/unit/templates/cordova/lib/prepare.spec.js
The project root path was undefined and prevent electron platform from adding.
This uses the correct object that always contains the project root path.
- `npm t`
- `cordova platform add ...`
=> Fix Bundle Feature's Project Path Issue & Warning Output

package.json
none
There was a discrepancy between the `package.json` and `package-lock.json`.
This PR sets `package.json` to match with `package-lock.json` and prepare for the minor release.
Updated `package.json`
none
=> Fixed package.json Version to 1.1.0-dev

package-lock.json, package.json
none
https://github.com/apache/cordova/issues/121
- Bump dependency `cordova-common` to version `^3.2.0`
- `npm t`
- CI
- Run Test
```
cordova create test1 com.foobar.test1 test1 && $_
cordova platform add github:erisu/cordova-electron\#bump-cordova-common-3.2.0
cordova run electron --nobuild
```
=> Bump cordova-common@^3.2.0

package-lock.json, package.json
electron
https://github.com/apache/cordova/issues/121
This PR bumps the `fs-extra` dependency to `^8.0.1`.
- `npm t`
- CI
=> Bump dependency fs-extra@^8.0.1

package-lock.json, package.json
none
v1.1.0 Release Preparations
- `eslint@^5.12.0` → `eslint@^5.16.0`
- `eslint-plugin-import@^2.14.0` → `eslint-plugin-import@^2.17.3`
- `eslint-plugin-promise@^4.0.1` → `eslint-plugin-promise@^4.1.1`
- `jasmine@^3.3.1` → `jasmine@^3.4.0`
- `nyc@^13.1.0` → `nyc@^14.1.1`
- `npm t`
=> Update Development Dependencies for v1.1.0

bin/templates/cordova/lib/build.js, tests/spec/unit/templates/cordova/lib/build.spec.js
Allow leveraging more Electron Builder options.
Resolves  #72, #74
Append [Overridable per Platform Options](https://www.electron.build/configuration/configuration#overridable-per-platform-options) build configuration. 
As well, the top-level [macOS](https://www.electron.build/configuration/mac), [Windows](https://www.electron.build/configuration/win), [Linux](https://www.electron.build/configuration/linux) key options. 
`npm t`
- ~~[ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)~~
=> Append overridable/top-level per platform options

bin/templates/cordova/version
`cordova platform ls`  =>  does not reflect the correct version. 
coho is suppose to update this files version but seems to not be configured for Electron properly.
This PR is to fetch the version from `package.json` instead of having coho update this file.
- `cordova platform ls`
- `npm t`
=> Updated Version to Return from `package.json`

tests/spec/unit/templates/cordova/lib/build.spec.js, tests/spec/unit/templates/cordova/lib/clean.spec.js, tests/spec/unit/templates/cordova/lib/run.spec.js
Code coverage displayed inaccurate results for node 12 because rewiring process was not working.
Applied spyOn to rewire the global process sub properties such as  `exit`, `env` etc.
- `npm t`
- [Travis CI](https://travis-ci.org/erisu/cordova-electron/builds/557721740)
=> fix: use spyOn for process global var

tests/spec/unit/create.spec.js
Speed up the tests.
Currently, the tests run a create and build step of various projects with various names. (ASCII and Unicode combinations).
Since Electron never supported the platform-centric workflow, these binaries do not work. For example `create` and `version` will work but `run` and `build` fails.
Since there is no current plan for platform-centric workflow in the Cordova Electron platform, it is not necessary to test these.
Instead, I kept one create the test with a verify step that ensures the binaries are copied to the right locations.
Second, for the various name tests, I used the create API to create an empty folder with the name and verified the folder name.
If we decide that its better to remove these un-used binaries and remove the tests altogether, we can do this in a …
=> refactor: improve create test spec speed

bin/templates/cordova/lib/PackageJsonParser.js, tests/spec/unit/templates/cordova/lib/PackageJsonParser.spec.js
fixes: #87 
The code tries to read the `dependencies` property from the `package.json` and is expected to be an `object`. Since the property in this case did not exist, it is `undefined` and the code there after fails.
I have added a wrapper to check if the `dependencies` property exists before continuing.
- `npm t`
=> fix: prepare missing dependencies failure

package-lock.json
none
Preparing `1.1.1` patch release shows audit warning with current `package-lock.json`.
```
found 19 high severity vulnerabilities
```
This PR is to update the `package-lock.json` to update the sub-dependnecies which triggers the warnings.
- `npm t`
=> chore: rebuilt package-lock.json for audit fix

DOCUMENTATION.md, bin/templates/cordova/lib/SettingJsonParser.js, bin/templates/cordova/lib/prepare.js, bin/templates/project/cdv-electron-main.js, tests/spec/unit/templates/cordova/lib/SettingJsonParser.spec.js, tests/spec/unit/templates/cordova/lib/prepare.spec.js
Resolves #80 
Objects created with `new BrowserWindow` have instance methods, one of such is `loadURL`. Previously we have loaded `{project_dir}/www/index.html` file explicitly. This PR adds an ability to change the start page.
- By default, `loadURL` loads a local HTML file which should be defined in `config.xml` under `content` tag.
- Possible to override this option in the Electron settings file. (More info in the `DOCUMENTATION.md`)
`npm t` 
Manually tested with the following Electron settings files:
```json
"browserWindowInstance": {
"loadURL": {
"url": "custom.html"
}
}
```
```json
"browserWindowInstance": {
"loadURL": {
"url": "https://cordova.apache.org"
}
}
```
```json
"browserWindowInstance": {
"loadURL": {
"url": "https://cordova.apache.org",
"options": {
"extraHeaders": …
```
=> Load a local HTML file or remote a URL in the BrowserWindow

.github/workflows/ci.yml, .travis.yml, package-lock.json, package.json
Use GitHub Actions instead of third-party CI services.
* Created GitHub Actions Task
* Move all Travis CI jobs to GitHub Actions
* Run only one Travis CI job for `codecov` reports. (Job Environment: Linux + Node 12)
Codecov has a better UI but requires setting secrets in GH which we do not have the direct ability to set. If we want to continue supporting and using Codecov, we would need to community with INFRA to set the secret token.
- See `Actions` tab (https://github.com/erisu/cordova-electron/actions)
=> feat: move ci to gh-actions

bin/templates/cordova/lib/run.js, package-lock.json, package.json, tests/spec/unit/create.spec.js, tests/spec/unit/templates/cordova/lib/run.spec.js
Use `execa` instead of using `child_process` (spawn) & `shelljs.exec`.
Removed `shelljs.exec` and `spawn`
- `npm t`
- `cordova run electron --nobuild`
=> refator: replace shelljs.exec & spawn with execa

bin/templates/cordova/lib/prepare.js, package-lock.json, package.json, tests/spec/unit/templates/cordova/lib/prepare.spec.js
Remove `shelljs` dependency in favor of using `fs-extra`
https://issues.apache.org/jira/projects/CB/issues/CB-14140
* Removes `shelljs` dependency.
* Added `execa`
* Cleanup test
- `npm t`
=> refactor: remove shelljs and update tests

bin/templates/cordova/lib/PackageJsonParser.js, bin/templates/cordova/lib/prepare.js, tests/spec/unit/templates/cordova/lib/PackageJsonParser.spec.js
Build fails when the `package.json` contains a dependency that is from the local file system and is a relative path.
This PR adds to the prepare step for the App's `package.json` to convert relative paths to absolute paths. If the converted path does not exist, it will be drop from being added to the App's `package.json` and a warning is displayed.
- `npm t`
- platform add, prepare, and build
=> chore: configure app rel dependencies as abs paths

bin/lib/create.js, bin/templates/cordova/Api.js, bin/templates/cordova/version, tests/spec/unit/Api.spec.js
Fix failing tests that are triggered by the combination of latest node version 12.16.0+, files containing shebang, and rewire linter.
Example Error:
```
SyntaxError: Invalid or unexpected token
at new Script (vm.js:88:7)
at createScript (vm.js:263:10)
at Object.runInThisContext (vm.js:311:10)
at wrapSafe (internal/modules/cjs/loader.js:1059:15)
at Module._compile (internal/modules/cjs/loader.js:1122:27)
```
* Removed shebang from JS files.
* JS files should not load `bin` files with `require`.
* Moved the `version` logic into `Api.js` and updated the `version` bin file to call `Api.js`
- `npm t`
- `cordova platform add`
=> test (node-12.16.x): fix failures caused by shebang and rewire lint

DOCUMENTATION.md, lib/run.js, tests/spec/unit/lib/run.spec.js
Add the ability to pass Electron arguments to the run command.
This feature, for example, can allow users the pass the flag which enabled the ability to debug the main process.
**Example Commands**
* `--inspect=[port]`
* `--inspect-brk=[port]`
**Example Usage**
```shell
cordova run electron --nobuild -- --inspect-brk=5858
```
- `npm t`
=> feat: support electron arguments on run command

package-lock.json, package.json
Since the official `cordova-common@4.0.1` is released, we can now bump to the official release and stop using the nightly version.
- `npm t`
=> chore: bump cordova-common 4.0.1

lib/build/base.json, package-lock.json, package.json
- Use latest released `electron@^9.0.0`
- Node: 12.14.1
- Chromium: 83.0.4103.64
- Use latest `electron-builder` to support deep signing that is required with latest Electron
Chromium: 83.0.4103.64 fixes issues with darkmode.
- `npm t`
- `cordova build`
- `cordova run`
=> breaking: bump electron & electron-builder

lib/build.js, tests/spec/unit/lib/build.spec.js
Some build targets has configurations and are stored in a top-level key.
For example: if the target `dmg` is set, there is a `top-level` node in the configuration structure called `dmg` which contains its configurations.
Not all `top-level` keys match the `target` key. 
For example: `nsis-web` target key actually has a top-level key of `nsisWeb`
This PR adds a target key to top-level key mapping. If the target key exists in this mapping, it will use the defined top-level key else fall back to the target key.
- `npm t`
- `cordova platform add`
- `cordova build electron`
=> fix(build): format top-level key for nsis-web

lib/Api.js, tests/spec/unit/lib/Api.spec.js
There are possibilities that the Cordova-Lib's version of Cordova-Common does not matching the platform's version. There can be cases where the platform introduces supporting logic in common and pins itself to use the new version.
A good example where this case happened in the past was with Adaptive Icons in Cordova Android. Supportive logic was added to common and the platform was pinned but anyone who used the latest platform had issues with adaptive icon because the Lib version of common which was passed to platform and used during prepare was old.
It is expected that platform's common can be updated to a version that lib does not use.
This PR will recreate the common object during prepare with the platform's installed common.
- `npm t`
=> breaking: use platform's common config parser

DOCUMENTATION.md, bin/templates/platform_www/cdv-electron-main.js, lib/Api.js, lib/PackageJsonParser.js, lib/prepare.js, lib/util.js, package-lock.json, package.json, tests/spec/unit/lib/Api.spec.js, tests/spec/unit/lib/PackageJsonParser.spec.js, tests/spec/unit/lib/prepare.spec.js
- Added support to install & enable developer tool extension
- Centralize the fetching of platform's `package.json` in `util.js`
- Updated `Api.version` to use centralized fetch method
- Updated `Api.version` unit-test
- New feature uses centralized fetch method
- Added unit test for new feature
**Details on New Feature**
- New feature uses the dependency `electron-devtools-installer` to install the devtool extensions that are on Chrome App Store during project build.
- This dependency is added to the Electron project only for debug builds.
- Cordova's implementation does not support adding this dependency in any way to a release build.
- The dependency pre-provided extension keys to quickly install without knowing an ID [`electron-devtools-installer` Extension …
=> feat: install devtool extensions for debug builds

lib/build/base.json, package-lock.json, package.json
Final dependencies bump before Cordova-Electron 2.0.0 Release prepare.
This PR:
- bumps `electron@^10.1.2` : [Change Log](https://github.com/electron/electron/releases/tag/v10.1.2)
- bumps `electron-builder@^22.8.1` : [Change Log](https://github.com/electron-userland/electron-builder/releases/tag/v22.8.1)
- rebuilds `package-lock.json`
- `npm t`
=> chore: bump dependencies & related usage

bin/templates/cordova/Api.js, lib/Api.js, lib/run.js, tests/spec/unit/lib/run.spec.js
The use of globals in the bridge Api broke a few use-cases:
- loading the bridge Api from two different locations
- requiring `cordova-electron` without setting the globals first
This change refactors the run module back to an "extension method" of `Api`. That is, it has to be called with `this` set to an `Api` instance. This pattern is also used for `build` and `run` and it is pretty common among the other platforms as well.
- I have updated the `run` unit test
- All automated tests pass
=> fix(Api): do not depend on globals

package.json
Related to https://github.com/apache/cordova/issues/55
=> fix(pkg): typo in field "keywords"

.eslintignore, bin/templates/platform_www/cdv-electron-main.js, bin/templates/platform_www/cdv-electron-preload.js, cordova-js-src/exec.js, cordova-lib/cordova.js, lib/Api.js, lib/PackageJsonParser.js, lib/handler.js, lib/parser.js, lib/prepare.js, tests/spec/fixtures/test-app-with-electron-plugin/config.xml, tests/spec/fixtures/test-app-with-electron-plugin/package.json, tests/spec/fixtures/test-app-with-electron-plugin/platforms/electron/config.xml, tests/spec/fixtures/test-app-with-electron-plugin/platforms/electron/cordova/Api.js, tests/spec/fixtures/test-app-with-electron-plugin/platforms/electron/cordova/defaults.xml, tests/spec/fixtures/test-app-with-electron-plugin/platforms/electron/cordova/version, tests/spec/fixtures/test-app-with-electron-plugin/platforms/electron/cordova/version.bat, tests/spec/fixtures/test-app-with-electron-plugin/platforms/electron/electron.json, tests/spec/fixtures/test-app-with-electron-plugin/platforms/electron/platform_www/config.xml, tests/spec/fixtures/test-app-with-electron-plugin/platforms/electron/www/config.xml, tests/spec/fixtures/test-app-with-electron-plugin/platforms/electron/www/cordova_plugins.js, tests/spec/fixtures/test-app-with-electron-plugin/platforms/electron/www/package.json, tests/spec/fixtures/test-app-with-electron-plugin/plugins/cordova-plugin-device/package.json, tests/spec/fixtures/test-app-with-electron-plugin/plugins/cordova-plugin-device/plugin.xml, tests/spec/fixtures/test-app-with-electron-plugin/plugins/cordova-plugin-device/src/electron/index.js, tests/spec/fixtures/test-app-with-electron-plugin/plugins/cordova-plugin-device/src/electron/package.json, tests/spec/fixtures/test-app-with-electron-plugin/plugins/cordova-plugin-device/www/device.js, tests/spec/fixtures/test-app-with-electron-plugin/www/index.html, tests/spec/unit/lib/PackageJsonParser.spec.js, tests/spec/unit/lib/handler.spec.js
* To create proper plugin support for Electron with Cordova's existing plugin system.
* To use a more secure and reliable way for loading remote content with out node integration. Use of `contextIsolation` & `preload`
* Added ICP handler for plugin communication in the main process.
* API Change to pass plugin dir path to uninstall step for framework.
* Added framework un/install support with necessary parser changes.
* Added an exclusion to not overwrite the platform's installed `node_modules` and `package.json`
* Updated the `exec` method to support he new electron implementation but keep the browser fallback when electron is missing.
* Add the Cordova Electron's custom preload which is used to as a bridge between Cordova's `exec` & Electon's native `ipcRenderer`.
* Updated …
=> breaking: add plugin support

lib/build/base.json, package-lock.json, package.json
Use latest dependencies:
* Bump Dependencies
* electron@11.1.1
* electron-build@^22.9.1
* execa@^5.0.0
* Electron is pinned for builds 11.1.1
Since Cordova-Electron 2.x is using Electron 10.1.2, there has been various fixes, security patches, new features and one breaking change introduced though all the version up to Electron 11.1.1.
Below I have outlined the main changes, but for a full list please review Electon's Change Log at: https://www.electronjs.org/releases/stable
* Chromium 87.0.4280.47
* Node v12.18.3
* V8 v8.7
* Removed experimental APIs: BrowserView.{destroy, fromId, fromWebContents, getAllViews} and the id property of BrowserView.
* Removed the faulty emulated ENOENT error on Windows. https://github.com/sindresorhus/execa/releases/tag/v5.0.0
- `npm t`
- `cordova run …
=> breaking(dependencies): bump electron, electron-builder & execa

lib/run.js, tests/spec/unit/lib/run.spec.js
- Windows (electron window is hidden)
- others (stdio is ignored)
On windows platform using nodejs 11+, the electron window does not appear.
`windowsHide: false` makes the electron window appear on windows.
I manually tested my changes on windows.
=> fix(windows): electron window not displaying

lib/build/base.json, package-lock.json, package.json
Keep the Electron dependency updated for next major release. Since master is already pinned for next major, we can continue to bump in the majors.
- `npm t`
- `cordova platform add`
=> breaking: bump electron@12.0.1

.github/workflows/ci.yml, package.json
Drop support for node 10.x and lower. Node 10.x has reached the EoL (2021-04-30). 
It is recommended that users upgrade node to at least 12.x or higher. Node 12.x is currently in maintenance mode and will reach its EoL sometime around 2022-04-30.
- Dropped node 10.x from GH Actions strategy.
- Added node 16.x to GH Actions strategy.
- Bump node engine requirement to `>=10.0.0`.
- `npm t`
=> feat!: update node support

lib/Api.js, tests/spec/unit/lib/Api.spec.js
While cleaning up, saw these unused location paths. Removing them but flaging as a breaking change.
* `Api.js`
* The `cordovaJs` location was removed as it was not used anywhere in code except for tests.
* Appears to be leftover code from other platforms but also not used in those platforms as well
* path is also old and not correct anymore. It changed in an earlier PR which restructured the platform.
* The `cordovaJsSrc` location was removed as it was not used anywhere in code except for tests.
* Appears to be leftover code from other platforms but also not used in those platforms as well
- `npm t`
=> feat!(Api): remove unused locations data

lib/handler.js
Installing Cordova Electron plugins does not install the Electron scope dependencies since npm 8.
Might be related to: https://github.com/npm/cli/issues/2339
This PR will `npm install` the sub-package dependencies before installing the sub-package to the Electron app scope.
The only potential side-efect is a slight increase in performance, but this resolves the changes that were made in npm 7 or 8.
npm 8 will only create a symlink to the sub-package without installing.
- `npm t`
- `cordova run` with `cordova-plugin-device` installed.
=> fix: npm 8 does not install plugin dependencies

package-lock.json, package.json
Fixes the "ENOENT. spawn /usr/bin/python" error during build.
Resolves #220
This error is coming from the `electron-builder` dependency. The issue was resolved in the latest major release `23.x`.
For more information, see: https://github.com/electron-userland/electron-builder/issues/6726
In this PR:
- Bumped npm package dependency `electron-builder@^23.0.3`
Use the npm 8 `overrides` property:
```json
"overrides": {
"cordova-electron": {
"electron-builder": "^23.0.3"
}
}
```
The environment will require `node >=14.14` and `npm >= 8` with this workaround.
`npm t`
=> fix: ENOENT. spawn /usr/bin/python

bin/templates/platform_www/cdv-electron-main.js, package-lock.json, package.json
electron
update to use latest released electron
* Bump `electron` dependency to `^29.0.0`
* Replace deprecated usage `protocol.registerFileProtocol` with `protocol.handle`
* Remove deprecated usage `protocol.interceptFileProtocol`
* Disabled `sandbox` setting. (When sandbox is enabled, appears that preload scripts and other require statements fails).
* Future Task: Review and determin if we can support `sandbox` as optional, or completely migrate to `sandbox`. Needs to support Cordova plugin ecosystem. (third-party npm package support)
* Simple plugin test with `cordova-plugin-device`
* Confirmed that the native `bridge` communication still functions and results are fetched by third-party npm package and returned to front with method `window.device.getInfo(e => console.log(e));`
* `npm t` …
=> feat!: bump electron@^29.0.0 w/ supporting changes

.github/workflows/ci.yml
n/a
Appears codecov v4 has issues with tokenless support
Downgraded back to v3 which worked.
n/a
=> ci: downgrade codecov action dependency to v3

.github/workflows/ci.yml, tests/spec/fixtures/test-app-with-electron-plugin/plugins/cordova-plugin-sample/src/electron/index.js, tests/spec/fixtures/test-app-with-electron-plugin/plugins/cordova-plugin-sample/www/sample.js
n/a
CodeQL scanning in CI can help identify bugs and security issues with the library.
* Added CodeQL scanning with default options as part of CI.
* Ran this in my fork
* Confirmed that CodeQL results showed up under security scanning 
* Applied additional non-breaking changes to resolve scan reports.
=> ci: Set up CodeQL analysis w/ fix

bin/templates/platform_www/cdv-electron-main.js, lib/Api.js, lib/ManifestJsonParser.js, lib/PackageJsonParser.js, lib/SettingJsonParser.js, lib/build.js, lib/clean.js, lib/create.js, lib/handler.js, lib/parser.js, lib/prepare.js, lib/run.js, package-lock.json, package.json, tests/spec/unit/lib/Api.spec.js, tests/spec/unit/lib/ManifestJsonParser.spec.js, tests/spec/unit/lib/PackageJsonParser.spec.js, tests/spec/unit/lib/SettingJsonParser.spec.js, tests/spec/unit/lib/build.spec.js, tests/spec/unit/lib/clean.spec.js, tests/spec/unit/lib/create.spec.js, tests/spec/unit/lib/handler.spec.js, tests/spec/unit/lib/parser.spec.js, tests/spec/unit/lib/prepare.spec.js, tests/spec/unit/lib/run.spec.js, tests/spec/unit/lib/util.spec.js
n/a
Modernaize code
- Use Node Internal Modules `node:*`
- Replace `fs-extra` with `node:fs`
- Improve PackageJsonParser testing
- `npm t`
=> refactor: use node internal modules & replace fs-extra with node:fs
