bin/templates/cordova/build
bin/templates/cordova/clean
bin/templates/cordova/lib/build.js
bin/templates/cordova/lib/clean.js
bin/templates/cordova/lib/run.js
bin/templates/cordova/run

electron
- Refactor's the binaries to be more consistent between each other. 
- This PR does not fix the issues within the existing workflow of the binaries usage. The workflow is currently in the requirements phase.
```
$ npm t
```

Cleanup Bin Files

---

.npmignore

electron
- Removes files not needed to be in the NPM deployment package.
Example Files:
- Testing configurations
- Unit tests
- Code coverage reports
```
$ npm pack
```

Added NPM Ignore File

---

DOCUMENTATION.md
tests/spec/unit/templates/cordova/lib/prepare.spec.js

------------------------------------------
------------------------------------------
Electron
------------------------------------------
------------------------------------------
Related to issue #14 
Update the documentation and implement unit tests missing in PR #8 
------------------------------------------
------------------------------------------
Since there were no code changes, I just ran automated tests.
```
64 specs, 0 failures
Finished in 534.496 seconds
-----------------------|----------|----------|----------|----------|-------------------|
File                   |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-----------------------|----------|----------|----------|----------|-------------------|
All files              |    44.39 |    35.14 |    31.52 | …
```

Implement unit tests and update the documentation for PR #8

---

package-lock.json

none
Remove the high severity vulnerability.
```
=== npm audit security report ===
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nyc [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nyc > istanbul-reports > handlebars                          │
├───────────────┼──────────────────────────────────────────────────── …
```

Fix Audit Report For High Severity Vulnerability

---

tests/spec/unit/lib/update.spec.js
tests/spec/unit/templates/cordova/lib/clean.spec.js
tests/spec/unit/templates/cordova/lib/run.spec.js

none
Test Coverage
Added Test Specs for:
- Update
- Clean
- Run
- `npm t`
- [Travis CI](https://travis-ci.org/erisu/cordova-electron/builds/495280618)
- [Code Coverage](https://codecov.io/gh/erisu/cordova-electron)

Adding New Test Specs

---

bin/templates/cordova/lib/build.js

electron
This is related to issue #26 
Emit warm messages using event emitter to improve the usability and give users more insights about the errors and signing configurations that they should provide.
Added emits for better usability. Also, spotted and removed unused argument in the __configureUserBuildSetting__ method.
npm t

Build Script Improvements

---

DOCUMENTATION.md

electron
Update Electron documentation.
Update Electron's system requirements.
npm t
- [ x] I've updated the documentation if necessary

Update System Requirements

---

DOCUMENTATION.md

none
- Updating Doc Formatting
- Correct nodeIntegration Usage
Same as **Motivation**
none

Updated DOCUMENTATION.md

---

bin/templates/cordova/lib/build.js
tests/spec/unit/templates/cordova/lib/build.spec.js

Fix typo
Fix typo in build. From "Singning" to "Signing".
`npm t`
- ~~[ ] I added automated test coverage as appropriate for this change~~
- ~~[ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)~~

Fix typo in build: "Singning" -> "Signing"

---

bin/templates/cordova/lib/prepare.js
tests/spec/unit/templates/cordova/lib/prepare.spec.js

Fixes #78 
Icons not matching requirements should be ignored and should not break the build if at least one correct icon is found.
`npm t`
Manually tested with the following `electron` platform configurations in the `config.xml` file:
```xml
...
<platform name="electron">
<icon src="res/electron/icon.png" />
</platform>
...
```
```xml
...
<platform name="electron">
<icon src="res/electron/app.png" target="app" />
<icon src="res/electron/installer.png" target="installer" />
</platform>
...
```
```xml
...
<platform name="electron">
<icon src="res/electron/icon.png" />
<icon src="res/electron/icon@1.5x.png" />
<icon src="res/electron/icon@2x.png" />
<icon src="res/electron/icon@4x.png" target="installer" />
</platform>
...
```
```xml
...
<platform name="electron">
<icon …
```

Filter icons only matching requirements

---

.travis.yml
bin/templates/cordova/Api.js
bin/templates/cordova/handler.js
bin/templates/cordova/lib/build.js
bin/templates/cordova/lib/build/base.json
bin/templates/cordova/lib/prepare.js
bin/templates/cordova/parser.js
package-lock.json
package.json
tests/spec/unit/Api.spec.js
tests/spec/unit/create.spec.js
tests/spec/unit/templates/cordova/lib/ManifestJsonParser.spec.js
tests/spec/unit/templates/cordova/lib/PackageJsonParser.spec.js
tests/spec/unit/templates/cordova/lib/build.spec.js
tests/spec/unit/templates/cordova/lib/prepare.spec.js
tests/spec/unit/templates/cordova/lib/util.spec.js
tests/spec/unit/templates/parser.spec.js

This contains previous PRs that has been merged into a feature branch (draft-2.0.0) for early testing.
This PR is to be `Rebase and merge` into master.
NOTE: https://github.com/apache/cordova-electron/pull/110 should be merged in before this PR.
Contains PR:
#69 
#68 
#67 
Additional changes will be handled outside of this PR. For example, replacing ESLint dependencies with `@cordova/config-eslint`
`npm t`

feat: draft 2.0.0

---

package.json
tests/spec/coverage.json

Update jasmine to support latest features.
Updated configs to be consistent with other repo configs.
- `npm t`

chore: update jasmine dependency

---

bin/templates/cordova/Api.js

Modernize code
Use `lebab` to apply `--transform let`. Minimum manual changes for lint fix.
- `npm t`

refactor: transform var to let/const

---

bin/templates/cordova/Api.js
tests/spec/unit/templates/cordova/lib/build.spec.js

Modernize code
Use `lebab` to apply `--transform obj-shorthand`.
- `npm t`

refactor: transform object shorthand

---

bin/templates/cordova/Api.js
bin/templates/cordova/handler.js
bin/templates/cordova/lib/prepare.js
bin/templates/cordova/parser.js
tests/spec/unit/Api.spec.js

Modernize code
Use `lebab` to apply `--transform template`.
- `npm t`

refactor: transform template strings

---

bin/templates/cordova/lib/prepare.js

Modernize code
Use `lebab` to apply `--transform for-of`.
- `npm t`

refactor: transform for

---

bin/templates/cordova/lib/build/base.json
package-lock.json
package.json

Continue to keep the Electron related dependencies updated for the next major release.
* electron@^7.1.2
- `npm t`
- `cordova run electron --nobuild`
- `cordova build electron`

chore: update electron dependencies

---

lib/PackageJsonParser.js
lib/build.js
lib/prepare.js
package-lock.json
package.json
tests/spec/unit/lib/SettingJsonParser.spec.js
tests/spec/unit/lib/handler.spec.js

Use updated ESLint configs
* Bump `@cordova/eslint-config@^3.0.0`
* Fix linting errors
- `npm t`

chore(npm): bump @cordova/eslint-config@^3.0.0 w/ lint fix

---

tests/spec/unit/lib/create.spec.js

Some things that caught my attention when reviewing #86

Fixes and cleanup for create-spec

---

package-lock.json
package.json

Use latest dependencies.
* Bumped Dev Dependencies:
* jasmine@^3.6.3
- `npm t`

chore(npm): bump dev dependencies for v3.x

---

lib/Api.js

Be Modern?
Use class static methods.
- `npm t`

refactor: use class static

---

lib/build/base.json
package-lock.json
package.json

Keep Electron related dependencies up-to-date
- `electron@13.2.2`
- `electron-builder@22.11.7`
- `electron-devtools-installer@3.2.0`
- `npm t`

feat!: upgrade electron dependencies

---

lib/build/base.json
package-lock.json
package.json

Use latest minor release of Electron 14.x
Bump `electron@^14.2.9`
`npm t`

feat: bump electron@^14.2.9

---

package-lock.json
package.json

Bump package for next major release.
Bump version to 4.0.0-dev
`npm t`

chore: bump version 4.0.0-dev

---

package-lock.json
package.json

Set the node engine requirement for the next major release
bump node engine requirement to 14.14.0
`npm t`

feat: bump node engine requirement >=14.14.0

---

package-lock.json
package.json

Use the latest electron package
bump npm package electron version to ^18.2.4
`npm t`
`cordova build`

feat: bump electron@^18.2.4

---

package-lock.json
package.json

Use latest major npm package dependencies
bump npm packages
`npm t`

dep(npm): bump dev dependencies

---

bin/templates/platform_www/cdv-electron-main.js
cordova-js-src/exec.js
package-lock.json
package.json
tests/spec/unit/lib/Api.spec.js

electron
Use latest dependencies and remove audit warnings from package-lock (development)
- bump rewire@^7.0.0
- bump jasmine@^5.1.0
- bump cordova-common@^5.0.0
- bump @cordova/eslint-config@^5.0.0 w/ lint fixes
- `npm t`

npm(dep)!: bump other dependencies

---

package-lock.json
package.json

n/a
use latest fs-extra dependency
update fs-extra to 11.2.0
* `npm t`
* `cordova platform add`
* `cordova plugin add`
* `cordova build`
* `cordova run`

dep!: bump fs-extra@^11.2.0

---

.github/workflows/release-audit.yml
.ratignore
licence_checker.yml

n/a
check license header and package dependency licenses during commit and pr submission
create release audit workflow
n/a

ci(gh-action): add Apache RAT & package license checker workflow
